services:
  backend_node_02:
    build: ./../airbnb-root/server
    command: java -jar server-0.0.1-SNAPSHOT.jar --server.port=5001
    volumes:
      - ./:/app/server/target/
    ports:
      - 5001:5001
networks:
  default:
   external:
     name: airbnb-network
