services:
  mongo_node_01:
    image: mongo:4.1.9
    entrypoint: [ "mongod","--port","27018","--bind_ip_all","--replSet", "rs0" ]
    container_name: 'mongo_instance'
    restart: unless-stopped
    ports:
      - 27018:27018
    networks:
      - airbnb-network


      #es:
      # image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
      #container_name: 'elastic_instance'
      #restart: unless-stopped
      #ulimits:
      #  memlock:
      #   soft: -1
      #  hard: -1
      #ports:
      # - 9200:9200
      #networks:
      # - airbnb-network


  backend_node_01:
    container_name: 'spring_instance'
    build: ./../airbnb-root/server
    command: java -jar server-0.0.1-SNAPSHOT.jar --server.port=5000
    volumes:
      - ./:/app/server/target/
    ports:
      - 5000:5000
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo_instance
      - SPRING_ELASTICSEARCH_REST_URIS=http://elastic_instance:9200
    depends_on:
      - mongo_node_01
    networks:
      - airbnb-network


networks:
  airbnb-network:
    driver: bridge
